var str = "UniversityOfKarachi";
console.log(str[0]); // U
console.log(str[1]); // n
console.log(str[2]); // i
console.log(str[3]); // v
console.log(str[4]); // e
console.log(str[5]); // r
console.log(str[6]); // s
console.log(str[7]); // i
console.log(str[8]); // t
console.log(str[9]); // y
console.log(str[10]); // o
console.log(str[11]); // f
console.log(str[12]); // K
console.log(str[13]); // a
console.log(str[14]); // r
console.log(str[15]); // a
console.log(str[16]); // c
console.log(str[17]); // h
console.log(str[18]); // i

document.write(str[0] + "<br>")
document.write(str[1] + "<br>")
document.write(str[2] + "<br>")
document.write(str[3] + "<br>")
document.write(str[4] + "<br>")
document.write(str[5] + "<br>")
document.write(str[6] + "<br>")
document.write(str[7] + "<br>")
document.write(str[8] + "<br>")
document.write(str[9] + "<br>")
document.write(str[10] + "<br>")
document.write(str[11] + "<br>")
document.write(str[12] + "<br>")
document.write(str[13] + "<br>")
document.write(str[14] + "<br>")
document.write(str[15] + "<br>")
document.write(str[16] + "<br>")
document.write(str[17] + "<br>")
document.write(str[18] + "<br>")